# Generated by Django 3.0.2 on 2020-01-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecatalog', '0003_gameid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gameid',
            constraint=models.UniqueConstraint(fields=('game_id', 'user'), name='users_fav_game'),
        ),
    ]
