# Generated by Django 3.0.2 on 2020-01-30 11:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gamecatalog', '0005_gameid_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gameid',
            managers=[
                ('not_deleted_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
