# Generated by Django 3.0.2 on 2020-01-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecatalog', '0006_auto_20200130_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameID',
            new_name='Favourite',
        ),
    ]
