# Generated by Django 3.0.2 on 2020-01-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecatalog', '0008_auto_20200131_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='aggregated_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='aggregated_rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
