# Generated by Django 3.0.2 on 2020-01-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecatalog', '0009_auto_20200131_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
