# Generated by Django 3.0.2 on 2020-02-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecatalog', '0010_auto_20200131_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
