# Generated by Django 3.0.2 on 2020-02-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecatalog', '0011_auto_20200203_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='name',
            new_name='slug',
        ),
    ]
