# Generated by Django 3.0.2 on 2020-02-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecatalog', '0012_auto_20200204_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='url',
            new_name='image_url',
        ),
    ]
